import { ShoeItem } from "@/type/product";

export const dummyShoes: ShoeItem[] = [
  {
    id: 1,
    itemName: "NikeNike Air Zoom Pegasus 39Nike Air Zoom Pegasus 39Nike Air Zoom Pegasus 39 Air Zoom Pegasus 39",
    brandLogo: { name: "Nike", image: "https://example.com/nike-logo.png" },
    price: "$120",
    image: { id: 101, image: "https://example.com/nike-pegasus.png" },
    colors: ["Black", "White", "Blue"],
    match_data: { score: 92, recommended_size: "US 10" },
    favourite: true,
  },
  {
    id: 2,
    itemName: "Adidas Ultraboost 22",
    brandLogo: { name: "Adidas", image: "https://example.com/adidas-logo.png" },
    price: "$180",
    image: { id: 102, image: "https://example.com/ultraboost.png" },
    colors: ["White", "Grey"],
    match_data: { score: 88, recommended_size: "US 9.5" },
    favourite: false,
  },
  {
    id: 3,
    itemName: "Puma RS-X3 Puzzle",
    brandLogo: { name: "Puma", image: "https://example.com/puma-logo.png" },
    price: "$110",
    image: { id: 103, image: "https://example.com/puma-rsx3.png" },
    colors: ["Red", "Black", "Yellow"],
    match_data: { score: 85, recommended_size: "US 10.5" },
    favourite: false,
  },
  {
    id: 4,
    itemName: "New Balance 574 Classic",
    brandLogo: {
      name: "New Balance",
      image: "https://example.com/nb-logo.png",
    },
    price: "$90",
    image: { id: 104, image: "https://example.com/nb-574.png" },
    colors: ["Grey", "Navy"],
    match_data: { score: 95, recommended_size: "US 9" },
    favourite: true,
  },
  {
    id: 5,
    itemName: "Asics Gel-Nimbus 25",
    brandLogo: { name: "Asics", image: "https://example.com/asics-logo.png" },
    price: "$160",
    image: { id: 105, image: "https://example.com/gel-nimbus.png" },
    colors: ["Blue", "White"],
    match_data: { score: 90, recommended_size: "US 10" },
    favourite: false,
  },
];
